name = "PWARegression"
uuid = "420b95b6-fbf7-47f8-b887-b44160baf6bf"
authors = ["guberger <guillaume.berger@colorado.edu>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
